sudo: required
dist: trusty
language: python
python:
    - "2.7"
before_install:
    - sudo add-apt-repository -y ppa:kivy-team/kivy-daily
    - sudo apt-get update
    - sudo apt-get install -y python-kivy git
    - pip install pip
    - pip install setuptools
    - pip install wsgiref
    - git clone https://github.com/kivy/buildozer.git
    - cd buildozer && sudo python setup.py install
install:
    - ls -la
    - ls -la project
    - pwd
    - buildozer android debug
script: nosetests

# using kivy-daily: python-kivy-1.9.2-0 version and CI testing ;)
# dist: trusty means Trusty Beta (14.04) which have new Kivy
# auto build with buildozer
# ---

deploy:
  provider: releases
  api_key: ${GH_TOKEN_FROM_ENV}
  file: ${FILENAME}
  skip_cleanup: true
  on:
    tags: true

# how to get GH_TOKEN?
# https://blog.wyrihaximus.net/2015/09/github-auth-token-on-travis/
# auto release on tags
