language: python
python:
    - "2.7"
before_install:
    - sudo add-apt-repository -y ppa:kivy-team/kivy-daily
    - sudo apt-get update
    - sudo apt-get install -y \
    python-pip \
    build-essential \
    git \
    python \
    python-dev \
    ffmpeg \
    libsdl2-dev \
    libsdl2-image-dev \
    libsdl2-mixer-dev \
    libsdl2-ttf-dev \
    libportmidi-dev \
    libswscale-dev \
    libavformat-dev \
    libavcodec-dev \
    zlib1g-dev
    - sudo apt-get install python-kivy=1.9.2-0
install:
    - pip install pip
    - pip install setuptools
    - pip install wsgiref
script: nosetests

#    - sudo apt-get install kivy-example
# using daily: 1.9.2 version and CI testing ;)
# auto build
# ---


# buildozer run
# ---

#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true

# auto release on tags
