# auto build
language: python
python:
    - "2.7"
before_install:
# using daily: 1.9.2 version and CI testing ;)
    - sudo add-apt-repository -y ppa:kivy-team/kivy-daily
    - sudo apt-get install python-kivy
# sudo apt-get install kivy-example
install:
    - pip install pip
    - pip install setuptools
    - pip install wsgiref
script: nosetests

# buildozer run


# auto release on tags
#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true

