sudo: required
dist: trusty
language: python
python:
    - "2.7"
before_install:
    - sudo apt-get install -y python-opengl python-gst0.10 python-enchant python-dev
    - sudo apt-get install -y gstreamer0.10-plugins-good libgl1-mesa-dev-lts-quantal libgles2-mesa-dev-lts-quantal
    - sudo add-apt-repository -y ppa:kivy-team/kivy-daily
    - sudo apt-get update
    - sudo apt-get install -y python-kivy
    - pip install pip
    - pip install setuptools
    - pip install wsgiref
    - pip install --upgrade Cython>=0.23
    - git clone https://github.com/kivy/buildozer.git
    - cd buildozer
    - sudo python setup.py install
    - cd ..
    - sudo rm -rf buildozer
install:
    - buildozer android debug
script: nosetests

# using kivy-daily: python-kivy-1.9.2-0 version and CI testing ;)
# dist: trusty means Trusty Beta (14.04) which have new Kivy
# auto build with buildozer
# ---

deploy:
  provider: releases
  api_key: ${GH_TOKEN_FROM_ENV}
  file: "360-0.1-debug.apk"
  skip_cleanup: true
  on:
    tags: true
    branch: master

# how to get GH_TOKEN?
# https://blog.wyrihaximus.net/2015/09/github-auth-token-on-travis/
# auto release on tags
