sudo: required
dist: trusty
language: python
python:
    - "2.7"
before_install:
    - sudo add-apt-repository -y ppa:kivy-team/kivy-daily
    - sudo apt-get update
    - sudo apt-get install python-kivy git
    - git clone https://github.com/kivy/buildozer.git
install:
    - pip install pip
    - pip install setuptools
    - pip install wsgiref
    - cd buildozer && sudo python setup.py build && sudo pip install -e
script: buildozer android debug

# using daily: 1.9.2 version and CI testing ;)
# auto build
# ---


# buildozer run
# ---

#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true

# auto release on tags
